{% set version = "0.10" %}

package:
  name: glue-vispy-viewers
  version: {{version}}

source:
  fn: glue-vispy-viewers-{{version}}.tar.gz
  url: https://pypi.io/packages/source/g/glue-vispy-viewers/glue-vispy-viewers-{{version}}.tar.gz
  sha256: e76e8b470f3f7efaac9754e637b367f128f181b368931cc8c77002109c272a4a

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:

  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - numpy
    - pyopengl
    - glue-core >=0.13
    - matplotlib
    - qtpy
    - astropy >=1.1
    - pyqt 5.6.*

test:
  imports:
    - glue_vispy_viewers
    - glue_vispy_viewers.scatter
    - glue_vispy_viewers.volume

about:
  home: https://github.com/glue-viz/glue-vispy-viewers
  license: BSD 3-Clause
  summary: 3D viewers for Glue

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
