{% set version = "1.3.0" %}

package:
  name: glue-vispy-viewers
  version: {{ version }}

source:
  fn: glue-vispy-viewers-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/g/glue-vispy-viewers/glue_vispy_viewers-{{ version }}.tar.gz
  sha256: 4d3fe2a605c567977e546a9367f1f0eddc1cc0b2b3234e71aec66ec3669ed45e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:

  host:
    - python {{ python_min }}
    - pip
    - setuptools >=30.3
    - setuptools_scm

  run:
    - python >={{ python_min }}
    - numpy
    - pyopengl
    - glue-core >=1.13.1
    - echo >=0.6
    - scipy
    - matplotlib-base
    - vispy >=0.12.0
    - importlib-metadata
    - glfw
    - imageio

    # The following dependency is from the [jupyter] extra, we should always
    # include it here otherwise there is no mechanism for users to opt in.
    - jupyter-rfb

test:
  requires:
    - python {{ python_min }}
  imports:
    - glue_vispy_viewers
    - glue_vispy_viewers.scatter
    - glue_vispy_viewers.volume

about:
  home: https://github.com/glue-viz/glue-vispy-viewers
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 3D viewers for Glue based on Vispy

extra:
  recipe-maintainers:
    - astrofrog
