{% set version = "1.0.3" %}

package:
  name: glue-vispy-viewers
  version: {{ version }}

source:
  fn: glue-vispy-viewers-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/glue-vispy-viewers/glue-vispy-viewers-{{ version }}.tar.gz
  sha256: 7ad9f5beeb0f7117568e428f9e135589d82e77ef15b4ace3034bed82a99ec7ad

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:

  host:
    - python
    - pip
    - setuptools >=30.3
    - setuptools_scm

  run:
    - python
    - numpy
    - pyopengl
    - glue-core >=1.0
    - qtpy
    - scipy
    - astropy >=4.0
    - pillow
    - matplotlib-base
    - vispy >=0.6

test:
  imports:
    - glue_vispy_viewers
    - glue_vispy_viewers.scatter
    - glue_vispy_viewers.volume

about:
  home: https://github.com/glue-viz/glue-vispy-viewers
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 3D viewers for Glue based on Vispy

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
