{% set version = "1.2.2" %}

package:
  name: glue-vispy-viewers
  version: {{ version }}

source:
  fn: glue-vispy-viewers-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/glue-vispy-viewers/glue_vispy_viewers-{{ version }}.tar.gz
  sha256: 296a02901790f69a66f3a06749887235b8ce9028590f894e5ccb7d05372cf116

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:

  host:
    - python >=3.8
    - pip
    - setuptools >=30.3
    - setuptools_scm

  run:
    - python >=3.8
    - numpy
    - pyopengl
    - glue-core >=1.13.1
    - echo >=0.6
    - scipy
    - matplotlib-base
    - vispy >=0.12.0
    - importlib_metadata
    - glfw
    - imageio

test:
  imports:
    - glue_vispy_viewers
    - glue_vispy_viewers.scatter
    - glue_vispy_viewers.volume

about:
  home: https://github.com/glue-viz/glue-vispy-viewers
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 3D viewers for Glue based on Vispy

extra:
  recipe-maintainers:
    - astrofrog
