travis:
  secure:
    BINSTAR_TOKEN: JVaWxRmLmc9Oodc0/khJiAsxkR0MihrJUni0Meuqyvd2H8c8J4wAZF1twvrjwPoymzBmUyLnufJfJuiDMKEZ4/Rz26nK0r6XsxXOQCsE/DcCPidzAhiYbK7TaVoRMa6r1rfdHpZdyuYBnYnFJRZdYzZnDgVDdiBvmh5ZI30RnJYiddTIyFgNkGpqJ92QjJQXEwn5OkDZYbOVVUS7u1Bi8pj90Fe33X52Gs2QCPzgzfd4Bhu3AGovlIdVUvsmQ+GmjUSAYhlRd9q9O2D91/JW8rK3jZEcnOiydZsqoOMxje6o7K8hnaL6IDEQfxJ3lV2xEBES7rZEHBDGOX8eTYXFf8aXX5wh+ygc/MelSRzoPHqkMxqaYCK9uyKpG7tYcMttnQQUyHyXWkiNJchQ95bcAwQrBVmFujr99oFeX0qt8e6dsp7AiylE547RaXQz3gm3gybuWCnkSj9Pj6RdDURJVzAOziWmWRBidRLVVys0t0zR/nTzF6QEMHtCLnQLThJ4X3KLbuVZKfJx7DtFeT9PVTtGkOWFr0x02AohGQY7lxejMXXnolQjxKgycurbs9MokYuIwmI7Cn3BI7C7dlX4EjgYxRariDXGYgJz+CIVP2tP19dRpcO1vr3ehPyktN1UBATdVNFmbdsCwt0J+t73m91q+nqhZNeRo1mAFkOcoOk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
